SELECT SYSDATE FROM DUAL; 
SELECT ADD_MONTHS(SYSDATE,NUMBER) FROM DUAL; 
SELECT LAST_DAY(SYSDATE) FROM DUAL; 
SELECT NEXT_DAY(SYSDATE) FROM DUAL; 
SELECT MONTHS_BETWEEN(DATE,DATE) FROM DUAL; 
SELECT STR_TO_DATE('SYSDATE', '%d-%m-%Y') FROM DUAL; 
SELECT DATE_FORMAT('SYSDATE', '%d/%m/%Y') FROM DUAL; 
SELECT TO_DATE('SYSDATE', 'DD-MM-YYYY') FROM DUAL; 
SELECT TO_CHAR('SYSDATE', 'DD/MM/YYYY') FROM DUAL;
/* DATE FUNCTIONS */
SELECT SYSDATE FROM DUAL;
SELECT Add_months(SYSDATE,3) FROM DUAL;
SELECT Last_day(SYSDATE) FROM DUAL;
SELECT Next_day(SYSDATE,'TUE') FROM DUAL;
SELECT Months_between('13-AUG-24','13-JUL-22') FROM DUAL;

/* DATE CONVERSION FUNC */
SELECT to_char(TO_DATE('20-AUG-24','DD-MM-YY'),('DD/MON/YY')) FROM DUAL;
SELECT to_char(TO_DATE('20-AUG-24','DD-MM-YY'),('DDTH MON YYYY')) FROM DUAL;
SELECT to_char(TO_DATE('20/AUG/24','DD/MM/YY'),('DDSPTH MON,YY')) FROM DUAL;
