SELECT CEIL(2.5) FROM DUAL;
SELECT ABS(-39) FROM DUAL;
SELECT FLOOR(63.993) FROM DUAL;
SELECT ROUND(9.8345888,10) FROM DUAL;
SELECT MOD(10,2) FROM DUAL;

SELECT LOWER(‘MVGR’) FROM DUAL;
SELECT UPPER(‘mvgrcse’) FROM DUAL;
SELECT CONCAT(‘Mvgr’,’College’) FROM DUAL;
SELECT TRIM (‘ department ‘) FROM DUAL;
SELECT LENGTH(‘ Mvgr college of engineering ‘) FROM DUAL;

SELECT CURRENT_DATE FROM DUAL;
SELECT SYSDATE FROM DUAL;
SELECT SYSTIMESTAMP FROM DUAL
